In [1]:
import numpy as np

In [2]:
array1=np.array([1,2,3,4,5])

In [4]:
array2 = np.array([[1,2,3,4,5],
                   [1,2,3,4,5]])

In [5]:
print(array2)

[[1 2 3 4 5]
 [1 2 3 4 5]]


In [6]:
arr3d = np.array([
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ],
    [
        [10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]
    ],
    [
        [19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]
    ]
])

In [7]:
print(arr3d)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


In [8]:
arr4=np.zeros((2,5,4))

In [9]:
arr4

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [10]:
arr4=np.ones((2,5,4))

In [11]:
arr4


array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [13]:
np.arange(1,12)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [25]:
arr6=np.linspace(1,10,5)

In [26]:
print(arr6)

[ 1.    3.25  5.5   7.75 10.  ]


In [27]:
arr3d.ndim

3

In [29]:
arr3d.shape

(3, 3, 3)

In [30]:
arr3d.size

27

In [31]:
arr3d.dtype

dtype('int32')

In [33]:
list1=[1,2,3,4,5]

In [34]:
arraylist=np.array(list1)

In [35]:
print(arraylist)

[1 2 3 4 5]


In [36]:
array2*2

array([[ 2,  4,  6,  8, 10],
       [ 2,  4,  6,  8, 10]])

In [37]:
print(array2)
print(array2*2)

[[1 2 3 4 5]
 [1 2 3 4 5]]
[[ 2  4  6  8 10]
 [ 2  4  6  8 10]]


In [39]:
array2

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [40]:
array2[1,3]

4

In [41]:
array2[1][3]

4

In [42]:
array2[1,3] * array2[0,3]

16

In [43]:
array2*array2

array([[ 1,  4,  9, 16, 25],
       [ 1,  4,  9, 16, 25]])